export default {
  label: '搜索输入',
  icon: 'bi:input-cursor-text',
  field: '',
  type: 'input',
  colProps: { span: 24 },
  componentProps: {
    type: 'text',
    defaultValue: '',
    onSearch__func: '',
    onSearch__params: ['value'],
    change__func: '',
    change__params: ['value'],
    readonly: false,
    enterButton: true,
    size: 'middle',
    allowClear: true,
    showCount: false,
  },
};
