export default {
  label: '对话框',
  formItem: false,
  type: 'container',
  icon: 'ant-design:border-outlined',
  componentProps: {
    title: '对话框',
    width: 1000,
    slots: {},
    onOkButtonClick__func: '',
    onOkButtonClick__params: ['{_this,callback}'],
    onCancelButtonClick__func: '',
    //  onCancelButtonClick__params: ['params'],
    onDialogOpened__func: '',
    onDialogOpened__params: ['{fData,eData}'],
    onDialogBeforeClose__func: '',
    onDialogBeforeClose__params: ['{callback}'],
  },
  children: [],
};
