export default {
  label: '对话框',
  formItem: false,
  type: 'container',
  icon: 'ant-design:border-outlined',
  componentProps: {
    title: '对话框',
    type: 'Modal',
    width: 1000,
    slots: {},
    footerBtnText: '',
    onFooterBtnClick__func: '',
    onFooterBtnClick__params: [''],
    onOkButtonClick__func: '',
    onOkButtonClick__params: ['{_this,callback,utils}'],
    onCancelButtonClick__func: '',
    //  onCancelButtonClick__params: ['params'],
    onDialogOpened__func: '',
    onDialogOpened__params: ['{fData,eData,schema,findFormItem}'],
    onDialogBeforeClose__func: '',
    onDialogBeforeClose__params: ['{callback}'],
    isDetail: false,
    showDetailBack: false,
    maskClosable: true,
    showCancelBtn: true,
    showOkBtn: true,
    showFooter: true,
  },
  children: [],
};
