export default {
  label: '抽屉',
  formItem: false,
  type: 'container',
  icon: 'ant-design:border-outlined',
  componentProps: {
    title: '抽屉',
    slots: {},
    placement: 'right',
    footerBtnText: '',
    onFooterBtnClick__func: '',
    onFooterBtnClick__params: [''],
    onOkButtonClick__func: '',
    onOkButtonClick__params: ['{_this,callback,utils}'],
    onCancelButtonClick__func: '',
    onCancelButtonClick__params: ['params'],
    onDialogOpened__func: '',
    onDialogOpened__params: ['params'],
    onDialogBeforeClose__func: '',
    onDialogBeforeClose__params: ['params'],
    width: 378,
    zIndex: 1000,
    isDetail: false,
    showDetailBack: false,
    maskClosable: true,
    showCancelBtn: true,
    showOkBtn: true,
    showFooter: true,
  },
  children: [],
};
